- name: PREPARING TOMCAT
  hosts: all

  vars:
    tomcat_version: 8.5.12
    java_version: 1.8.0
    
  tasks:
  - name: Installing OpenJDK Java 1.8 
    yum: name=java-{{ java_version }}-openjdk state=present
    become: yes
    become_user: root

  - name: Adding a group "tomcat_as_group"
    group: name=tomcat_as_group
    become: yes
    become_user: root

  - name: Adding a user "tomcat_as"
    user: name=tomcat_as group=tomcat_as_group
    become: yes
    become_user: root

  - name: Downloading Tomcat 8
    get_url: url=http://archive.apache.org/dist/tomcat/tomcat-8/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz dest=/opt/apache-tomcat-{{ tomcat_version }}.tar.gz
    become: yes
    become_user: root
  
  - name: Creating a folder for Tomcat 8
    file: state=directory path=/opt/tomcat/ 
    become: yes
    become_user: root

  - name: Unarchiving Tomcat 8 distribution
    unarchive: copy=no src=/opt/apache-tomcat-{{ tomcat_version }}.tar.gz dest=/opt/tomcat/ creates=/opt/tomcat/{{ tomcat_version }}
    become: yes
    become_user: root

  - name: Renaming a folder according to the requirements
    command: mv /opt/tomcat/apache-tomcat-{{ tomcat_version }} /opt/tomcat/{{ tomcat_version }} creates=/opt/tomcat/{{ tomcat_version }}
    become: yes
    become_user: root

  - name: Changing ownership of Tomcat folder
    file: path=/opt/tomcat/ owner=tomcat_as group=tomcat_as_group state=directory recurse=yes
    become: yes
    become_user: root
 
  - name: Transforming a script into service
    copy: src=~/cm/ansible/day-1/tomcat.sh dest=/etc/init.d/tomcat remote_src=no force=yes mode=0755    
    become: yes
    become_user: root
  
  - name: Starting Tomcat as a service
    service: name=tomcat state=started 
    become: yes
    become_user: root
  
  - name: Checking the work (curl -IL)
    shell: sleep 15; curl -IL 127.0.0.1:8080


  - name: Checking PID (not changed)
    shell: sleep 5; ps -U tomcat_as

  - name: Checking uptime of Tomcat
    shell: sleep 5; ls -al /proc | grep tomcat_as


